// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThirdPartService.proto

package escudeler.example.apithirdpart.grpc;

public interface AuthorizeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AuthorizeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool authorized = 1;</code>
   * @return The authorized.
   */
  boolean getAuthorized();
}
