// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpeakService.proto

package escudeler.example.apispeak.grpc;

public interface SpeakRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpeakRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string peopleName = 1;</code>
   * @return The peopleName.
   */
  java.lang.String getPeopleName();
  /**
   * <code>string peopleName = 1;</code>
   * @return The bytes for peopleName.
   */
  com.google.protobuf.ByteString
      getPeopleNameBytes();
}
